---
language: python

python:
    - "3.7"

env:
    - TRAVIS=1

install:
    - pip install --upgrade pip
    - pip install -r requirements.txt -r requirements-dev.txt .

script:
    - py.test -rxs --cov=cgbeacon2 tests/

notifications:
    email: false

after_success:
    - coveralls
