###########
# BUILDER #
###########
FROM clinicalgenomics/python3.8-slim-bedtools-venv:1.0 AS python-builder

ENV PATH="/venv/bin:$PATH"

# Install dependencies
COPY . /temp

WORKDIR /temp
# Install requirements for the app and gunicorn, to serve app in prod settings
RUN pip install --no-cache-dir -r requirements.txt gunicorn


#########
# FINAL #
#########
FROM python:3.8-slim

LABEL about.license="MIT License (MIT)"
LABEL about.home="https://github.com/Clinical-Genomics/cgbeacon2"
LABEL about.documentation="https://clinical-genomics.github.io/cgbeacon2"
LABEL about.tags="beacon,Rare diseases,VCF,variants,SNP,NGS"

# Do not upgrade to the latest pip version to ensure more reproducible builds
ENV PIP_DISABLE_PIP_VERSION_CHECK=1
ENV PATH="/venv/bin:$PATH"
RUN echo export PATH="/venv/bin:\$PATH" > /etc/profile.d/venv.sh

# Copy the folder where bedtools was installed from builder image
COPY --from=python-builder /usr/local/bin /usr/local/bin

# Create a non-root user to run commands
RUN groupadd --gid 1000 worker && useradd -g worker --uid 1000 --shell /usr/sbin/nologin --create-home worker

# Copy virtual environment from builder
COPY --chown=worker:worker --from=python-builder /venv /venv

# Copy app dir to image
COPY . /home/worker/app

WORKDIR /home/worker/app

# Install the app
RUN pip install --no-cache-dir -e .

# Run the app as non-root user
USER worker

# make sure all messages always reach console
ENV PYTHONUNBUFFERED=1

ENV GUNICORN_WORKERS=1
ENV GUNICORN_THREADS=1
ENV GUNICORN_BIND="0.0.0.0:8000"
ENV GUNICORN_TIMEOUT=400

CMD gunicorn \
    --workers=$GUNICORN_WORKERS \
    --bind=$GUNICORN_BIND  \
    --threads=$GUNICORN_THREADS \
    --timeout=$GUNICORN_TIMEOUT \
    --proxy-protocol \
    --forwarded-allow-ips="10.0.2.100,127.0.0.1" \
    --log-syslog \
    --access-logfile - \
    --error-logfile - \
    --log-level="debug" \
    cgbeacon2.server.auto:app
