version: '3'
# usage:
# (sudo) docker-compose up
# (sudo) docker-compose down
services:
  mongodb:
    image: mongo:4.4.9
    container_name: mongodb
    networks:
      - beacon-net
    ports:
      - '27013:27013'
    expose:
      - '27013'

  beacon-cli:
    container_name: beacon-cli
    environment:
      MONGODB_HOST: mongodb
    build: .
    depends_on:
      - mongodb
    networks:
      - beacon-net
    command: add demo

  beacon-web:
    container_name: beacon-web
    environment:
      MONGODB_HOST: mongodb
    build: .
    depends_on:
      - mongodb
    networks:
      - beacon-net
    expose:
      - '6000'
    ports:
      - '6000:5000'
    command: run --host 0.0.0.0

networks:
  beacon-net:
    driver: bridge
    ipam:
      driver: default
