name: Publish to Docker Hub

on:
 release:
  types:
   - created

jobs:
  docker-image-CI:
   name: Docker Image CI
   runs-on: ubuntu-latest
   steps:
    - name: Get release version
      id: get_version
      run: echo ::set-output name=release_version::$(echo ${GITHUB_REF:10})
    - name: Check out the repo
       uses: actions/checkout@v2
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: clinicalgenomics/cgbeacon2
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ steps.vars.outputs.release_version }}"
