name: Tests and coverage
on: [pull_request]
jobs:
  Pytest_Codecov:
    runs-on: ubuntu-latest
    env:
      CGBEACON2_CONFIG: ../instance/config.py
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install required linux libs
      run: |
        sudo apt-get install curl libcurl4 libcurl4-openssl-dev gcc bedtools
    - name: Install repo and its dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install -e .
        pip install pytest
        pip install pytest-cov
    - name: Run pytest and write coverage report
      run: |
        pytest --cov=./ --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        flags: unittests
        files: ./coverage.xml
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: true
