name: Publish to Docker Hub both general image (clinicalgenomics/cgbeacon2) and gunicorn server image (clinicalgenomics/cgbeacon2-server) based on master branch. Triggered whenever a new release is created

on:
 release:
  types:
   - created

jobs:
  docker-image-CI:
   name: Docker Image CI
   runs-on: ubuntu-latest
   steps:
    - name: Check out git repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push general image to Docker
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: "clinicalgenomics/cgbeacon2:${{github.event.release.tag_name}}, clinicalgenomics/cgbeacon2:latest"

    - name: Build and push prod server image to Docker
      id: docker_server_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile-server
        push: true
        tags: "clinicalgenomics/cgbeacon2-server:${{github.event.release.tag_name}}, clinicalgenomics/cgbeacon2-server:latest"
