name: Python Pull Request Workflow
on: [pull_request]
jobs:

  qa:
    name: Quality check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install missing linux libraries
        run: |
          sudo apt-get install curl libcurl4 libcurl4-openssl-dev gcc
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
      - name: Run unit tests
        run: |
          pwd
          ls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
